# Generated by Django 4.2.7 on 2024-01-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_wallet_alter_wishlist_user_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
