# Generated by Django 5.0.1 on 2024-01-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_product_active'),
        ('userdetails', '0002_alter_wishlist_user_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminapp.variant'),
            preserve_default=False,
        ),
    ]
