# Generated by Django 4.2.7 on 2023-12-26 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField(default=0)),
                ('otp_created_at', models.DateTimeField(auto_now=True)),
                ('otp_expiry', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('phone_Number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('pro_pic', models.ImageField(upload_to='User/image/User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
