# Generated by Django 5.0.1 on 2024-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='referal_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
