# Generated by Django 4.2.7 on 2023-12-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product_details'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('payment_method', models.CharField(default='cash_on_delivery', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.address')),
                ('product', models.ManyToManyField(related_name='orders', to='adminapp.product')),
            ],
        ),
    ]
