# Generated by Django 5.0.1 on 2024-01-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_product_active'),
        ('cart', '0002_remove_cartitem_discount_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ManyToManyField(through='cart.OrderItem', to='adminapp.variant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='adminapp.variant'),
            preserve_default=False,
        ),
    ]
