# Generated by Django 4.2.7 on 2024-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_grand_total_cart_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
        ),
    ]
