# Generated by Django 4.2.7 on 2024-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='discnt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
