# Generated by Django 4.2.7 on 2023-12-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_grand_total_order_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
