# Generated by Django 4.2.7 on 2023-12-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
