# Generated by Django 4.2.7 on 2023-12-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Varient_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stock', models.IntegerField(default=0)),
                ('details', models.CharField(default='None', max_length=100)),
                ('description', models.TextField()),
                ('img1', models.ImageField(blank=True, upload_to='product_images')),
                ('img2', models.ImageField(blank=True, upload_to='product_images')),
                ('img3', models.ImageField(blank=True, upload_to='product_images')),
                ('img4', models.ImageField(blank=True, upload_to='product_images')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('varient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.varient_color')),
            ],
        ),
    ]
