# Generated by Django 5.0.1 on 2024-01-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
