# Generated by Django 5.0.1 on 2024-01-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_categoryoffer_productoffer_category_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='start_date',
        ),
    ]
