# Generated by Django 5.0.1 on 2024-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_remove_categoryoffer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
