# Generated by Django 5.0.1 on 2024-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_remove_coupon_active_remove_coupon_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_prcnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_prcnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
