# Generated by Django 5.0.1 on 2024-01-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_categoryoffer_discount_prcnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_prcnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_prcnt',
            field=models.IntegerField(default=0),
        ),
    ]
