# Generated by Django 5.0.1 on 2024-01-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_categoryoffer_discount_prcnt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='discount_prcnt',
            new_name='discount_prcntg',
        ),
    ]
