# Generated by Django 5.0.1 on 2024-01-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_categoryoffer_discount_prcntg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_prcnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_prcnt',
            field=models.IntegerField(default=0),
        ),
    ]
