# Generated by Django 5.0.1 on 2024-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_categoryoffer_discount_prcnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='discount_prcnt',
            field=models.TextField(default=0),
        ),
    ]
