# Generated by Django 5.0.1 on 2024-01-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_productoffer_discount_prcnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_prcnt',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_prcnt',
            field=models.TextField(default=None),
        ),
    ]
