# Generated by Django 5.0.1 on 2024-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_alter_categoryoffer_discount_prcnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
